version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: casdoor
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

  casdoor:
    image: casbin/casdoor:v1.464.0
    restart: always
    depends_on:
      db:
        condition: service_healthy
    entrypoint: /bin/sh -c "./server --createDatabase=true"
    environment:
      RUNNING_IN_DOCKER: "true"
      DRIVER_NAME: "postgres"
      DATA_SOURCE_NAME: "host=db port=5432 user=postgres password=123456 dbname=casdoor sslmode=disable"
    ports:
      - "8000:8000"
    volumes:
      - ./config:/conf

volumes:
  db_data:
